# Generated by Django 4.2.5 on 2023-10-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=21)),
                ('lname', models.CharField(max_length=21)),
                ('ismale', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=21)),
                ('cin', models.CharField(max_length=21)),
                ('cen', models.CharField(max_length=21)),
                ('info', models.CharField(max_length=4096)),
                ('bday', models.CharField(max_length=21)),
            ],
        ),
    ]
