# Generated by Django 4.2.5 on 2023-10-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=21, primary_key=True, serialize=False),
        ),
    ]
