# Generated by Django 5.0.2 on 2024-08-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(max_length=21),
        ),
    ]
