# Generated by Django 5.1.3 on 2025-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_person_id_alter_person_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bday',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cen',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='info',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ismale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
